name: Generate Datas

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Dá permissão para o bot criar a branch 'output' e salvar os arquivos
permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: tamycs
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica a animação na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
